version: '3.8'

services:
  ros2-dev:
    build: .
    container_name: ros2-bocchi-dev
    volumes:
      - .:/workdir
    ports:
      - "2222:22"  # Map host port 2222 to container port 22 for SSH
    working_dir: /workdir
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    privileged: true
    restart: unless-stopped