name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt update -qq && \
        sudo apt install -y -qq --no-install-recommends software-properties-common && \
        sudo apt install -qq -y --no-install-recommends \
        bc \
        bison \
        build-essential \
        ccache \
        cmake \
        curl \
        dfu-util \
        flex \
        gcc \
        git \
        gperf \
        jq \
        libffi-dev \
        libncurses-dev \
        libssl-dev \
        libusb-1.0-0 \
        make \
        ninja-build \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        srecord \
        unzip \
        wget \
        xz-utils \
        && sudo apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    - name: Install PlatformIO
      run: |
        curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
        python3 get-platformio.py
        rm get-platformio.py
        python3 -m pip install --break-system-packages pipx setuptools virtualenv
        python3 -m pipx ensurepath
        python3 -V
        mkdir -p /usr/local/bin
        ln -s /root/.platformio/penv/bin/platformio /usr/local/bin/platformio
        ln -s /root/.platformio/penv/bin/pio /usr/local/bin/pio
        ln -s /root/.platformio/penv/bin/piodebuggdb /usr/local/bin/piodebuggdb
        pio platform install raspberrypi
    - name: Build firmware
      run: pio run
